"""
SQLite index of all World Cup 2026 players.

Schema:
  players(id INTEGER PK, name TEXT, team TEXT, face_path TEXT, embedding BLOB,
          position TEXT, dob TEXT, club TEXT, height_cm INTEGER, caps INTEGER, goals INTEGER)

Data files live in the genai/ root directory (gitignored, generated by ETL).
"""
import sqlite3
import json
import numpy as np
from pathlib import Path

from genai.core.config import DATA_DIR

DB_FILE        = str(DATA_DIR / "players.db")
EMBEDDINGS_FILE = str(DATA_DIR / "embeddings.npy")
METADATA_FILE  = str(DATA_DIR / "metadata.json")

_conn: sqlite3.Connection | None = None


def _build(conn: sqlite3.Connection):
    """Create the players table and populate it from embeddings.npy + metadata.json."""
    conn.execute("""
        CREATE TABLE players (
            id        INTEGER PRIMARY KEY,
            name      TEXT NOT NULL,
            team      TEXT NOT NULL,
            face_path TEXT NOT NULL,
            embedding BLOB NOT NULL
        )
    """)

    matrix = np.load(EMBEDDINGS_FILE)
    with open(METADATA_FILE) as f:
        metadata = json.load(f)

    rows = [
        (
            i,
            m["name"],
            m["team"],
            m["face_path"],
            matrix[i].astype(np.float32).tobytes(),
        )
        for i, m in enumerate(metadata)
    ]
    conn.executemany(
        "INSERT INTO players VALUES (?, ?, ?, ?, ?)", rows
    )
    conn.commit()
    print(f"[db] Indexed {len(rows)} players in memory")


def get_conn() -> sqlite3.Connection:
    """Return the singleton SQLite connection, building the DB on first call."""
    global _conn
    if _conn is None:
        already_exists = Path(DB_FILE).exists()
        _conn = sqlite3.connect(DB_FILE, check_same_thread=False)
        _conn.row_factory = sqlite3.Row
        if not already_exists:
            if not Path(EMBEDDINGS_FILE).exists() or not Path(METADATA_FILE).exists():
                raise FileNotFoundError("Run python -m genai.pipeline first.")
            _build(_conn)
            print(f"[db] Saved to {DB_FILE}")
        else:
            print(f"[db] Loaded from {DB_FILE}")
    return _conn


def get_all_embeddings(embeddings_file: str = EMBEDDINGS_FILE) -> tuple[np.ndarray, list[sqlite3.Row]]:
    """Returns (matrix N×D, list of player rows) for fast batch similarity."""
    conn = get_conn()
    rows = conn.execute(
        "SELECT id, name, team, face_path FROM players ORDER BY id"
    ).fetchall()
    matrix = np.load(embeddings_file)
    return matrix, rows


def get_player(player_id: int) -> sqlite3.Row | None:
    """Fetch a single player row by primary key, including enriched stats columns."""
    return get_conn().execute(
        "SELECT id, name, team, face_path, position, dob, club, height_cm, caps, goals FROM players WHERE id = ?",
        (player_id,),
    ).fetchone()
